app/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the Closure to execute when that URI is requested.
  |
 */

Route::get('/login', 'AuthenticationController@showLogin');
Route::post('/login', 'AuthenticationController@processLogin');
Route::get('/logout', 'AuthenticationController@logout');

Route::get('/', function() {
    return Redirect::to('/tasks');
});

Route::group(array('before' => 'auth'), function() {
    Route::resource('/tasks', 'TaskController');
    Route::resource('/tags', 'TagController');
    Route::resource('/users', 'UserController');
});

Route::api(['version' => 'v1'], function() {
    // Route::resource('users', 'UserController');
});

Route::api(['version' => 'v2', 'prefix' => 'api'], function() {
    Route::resource('users', 'UserApiV2Controller');
});

app/models/Task.php
<?php

class Task extends Eloquent {

    protected $fillable = array('title', 'description', 'xp');
    public static $rules = array(
        'title' => 'required|alpha|min:2',
        'description' => 'required|alpha|min:10',
        'xp' => 'required|num'
    );
    protected $table = 'tasks';

    public function requiredTasks() {
        return $this->belongsToMany('Task', 'tasks_req', 'task_id', 'req_id');
    }

    public function isRequiredBy() {
        return $this->belongsToMany('Task', 'tasks_req', 'req_id', 'task_id');
    }

    public function tags() {
        return $this->belongsToMany('Tag', 'task_tags', 'task_id', 'tag_id');
    }

    public function steps() {
        return $this->hasMany('TaskStep');
    }

    protected static function boot() {
        parent::boot();
        static::deleting(function($task) { // called BEFORE delete()
            $task->isRequiredBy()->detach();
            $task->requiredTasks()->detach();
            $task->tags()->detach();
            foreach ($task->steps as $step) {
                $step->delete(); // Causes any child "deleted" events to be called
            }
        });
    }

}

?>

app/controllers/TaskController.php
<?php

class TaskController extends \BaseController {

    public function __construct(EloquentTaskRepository $taskRepository, EloquentTagRepository $tagRepository) {
        $this->taskRepository = $taskRepository;
        $this->tagRepository = $tagRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index() {
        $tasks = $this->taskRepository->all();
        return View::make('tasks.index')
                        ->with('tasks', $tasks);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create() {
        $tasks = $this->taskRepository->all();
        $tags = $this->tagRepository->getTop(10);
        return View::make('tasks.create2')
                        ->with('tasks', $tasks)
                        ->with('tags', $tags);
    }

    /*
     * show the form for creating new tags
     * @return Response
     */

    public function tags() {
        $tags = $this->taskRepository->all();
        return View::make('tags.tag')
                        ->with('tags', $tags);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store() {
        $input = Input::except('_token');
        $success = $this->taskRepository->create($input);
        if ($success)
            return Redirect::to('/tasks')
                            ->with('message', 'successfully created task')
                            ->with('type', 'success');
        else
            return Redirect::to('/tasks/create')
                            ->with('message', 'could not create task')
                            ->with('type', 'warning');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id) {
        $task = $this->taskRepository->find($id);
        $reqs = $this->taskRepository->getRequiredTasks($id);
        $steps = $this->taskRepository->getSteps($id);
        Return View::make('tasks.show')
                        ->with('task', $task)
                        ->with('steps', $steps)
                        ->with('reqs', $reqs);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id) {
        $task = $this->taskRepository->find($id);
        $tasks = $this->taskRepository->all();
        $tags = $this->tagRepository->getTop(10);
        $taskTags = $task->tags()->lists('name');
        $taskReqs = $task->requiredTasks()->lists('title');
        $steps = $this->taskRepository->getSteps($id);

        Return View::make('tasks.edit')
                        ->with('tasks', $tasks)
                        ->with('taskTags', $taskTags)
                        ->with('tags', $tags)
                        ->with('reqs', $taskReqs)
                        ->with('steps', $steps)
                        ->with('task', $task);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update($id) {
        $input = Input::except('_token');
        $success = $this->taskRepository->update($id, $input);
        if ($success)
            return Redirect::to('/tasks')
                            ->with('message', 'successfully updated task')
                            ->with('type', 'success');
        else
            return Redirect::to('/tasks/create')
                            ->with('message', 'could not update task')
                            ->with('type', 'warning');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id) {
        $response = $this->taskRepository->destroy($id);
        return $response;
    }

}

app/views/tasks/index.blade.php
@extends('layouts.dashboard')
@section('content')
<h1 class="page-header">Task overview</h1>

<div class="panel panel-default">
    <div class="panel-heading">Manage Tasks</div>
    <div class="panel-body">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12"> 
                <table id="table_tasks" class="table table-striped table-bordered" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>title</th>
                            <th>Description</th>
                            <th>XP</th>
                            <th>Tags</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>title</th>
                            <th>Description</th>
                            <th>XP</th>
                            <th>Tags</th>
                            <th>Action</th>

                        </tr>
                    </tfoot>

                    <tbody>
                        @foreach($tasks as $task)
                        <tr>
                            <td>{{$task->title}}</td>
                            <td>{{$task->description}}</td>
                            <td>{{$task->xp}}</td>
                            <td>
                                @foreach($task->tags()->lists('name') as $tag)
                                {{$tag}},
                                @endforeach

                            </td>
                            <td class="text-center button"><div class="btn-group">
                                    <a href="{{ URL::to('/tasks/'.$task->id) }}" class="btn btn-xs btn-info">details</a>
                                    <a href="{{ URL::to('/tasks/'.$task->id.'/edit') }}" class="btn btn-xs btn-primary">modify</a>
                                    <a href="javascript:deleteTask({{$task->id}});" class="btn btn-xs btn-danger">delete</a></div></td>
                        </tr>
                        @endforeach       
                    </tbody>
                </table>
                <a href="{{ URL::route('tasks.create') }}" class="btn btn-primary"> Create task </a>
            </div>
        </div>
    </div>
</div>
@section('scripts')
@parent
<script>
    $(document).ready(function() {
        $('#table_tasks').dataTable();
    });
</script>
@stop
@stop

app/views/tasks/show.blade.php
@extends('layouts.dashboard')
@section('content')
<h1 class="page-header">Task Details</h1>

<div class="col-md-12 well">
    <div id="summary">
        <table class="table table-bordered table-striped">
            <colgroup>
                <col class="col-xs-1">
                <col class="col-xs-7">
            </colgroup>
            <thead>
                <tr>
                    <th colspan="2" class="success">Basic info</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th>
                        Title
                    </th>
                    <td id="title">{{$task->title}}</td>
                </tr>
                <tr>
                    <th>
                        XP
                    </th>
                    <td id="xp">{{$task->xp}}</td>
                </tr>
                <tr>
                    <th>
                        Description
                    </th>
                    <td id="description">{{$task->description}}</td>
                </tr>
                <tr>
                    <th>
                        Tags
                    </th>
                    <td id="tags">
                        @foreach($task->tags->lists('name') as $tag)
                        {{$tag}}, 
                        @endforeach
                    </td>
                </tr>
                <tr>
                    <th>
                        Required Tasks
                    </th>
                    <td id="tasks">
                        @if(count($reqs)>0)

                        @foreach($reqs as $req)
                        {{$req->title}}, 
                        @endforeach
                        @else
                        <i>no tasks</i>
                        @endif
                    </td>
                </tr>
            </tbody>
        </table>

        <table class="table table-bordered table-striped">
            <colgroup>
                <col class="col-xs-1">
                <col class="col-xs-7">
            </colgroup>
            <thead>
                <tr>
                    <th colspan="2" class="success">Task Steps</th>
                </tr>
            </thead>
            <tbody id="summarySteps">
                @for($i = 0; $i < count($steps); $i++)
                <tr><th colspan="2" class="info">Step {{$i+1}} </th></tr>
                <tr><th>XP Weight</th><td>{{$steps[$i]->xp_weight}}</td></tr>
                @if($steps[$i]->type == 'StepText')
                <tr><th>Title</th><td>{{$steps[$i]->stepType->title}}</td></tr>
                <tr><th>Text</th><td>{{$steps[$i]->stepType->text}}</td></tr>
                @elseif($steps[$i]->type == 'StepQuestion')
                <tr><th>Question</th><td>{{$steps[$i]->stepType->question}}</td></tr>
                <tr><th>Answer</th><td>{{$steps[$i]->stepType->answer}}</td></tr>
                @endif
                @endfor
            </tbody>
        </table>
    </div>
</div>

</table>

@stop